export interface Empresa {
  slug: string;
  nombre: string;
  categoria: string;
  pais: string;
  descripcion: string;
  telefono?: string;
  whatsapp?: string;
  email?: string;
  website?: string;
  instagram?: string;
  facebook?: string;
  direccion?: string;
  logoColor: string;
  logoText: string;
  badge?: number;
  destacado?: boolean;
  premium?: boolean;
  patrocinado?: boolean;
  tags?: string[];
  catalogos?: { nombre: string; url: string }[];
}

export interface Categoria {
  slug: string;
  nombre: string;
  emoji: string;
  color: string;
  badge?: number;
}

export interface Pais {
  slug: string;
  nombre: string;
  bandera: string;
  color: string;
}

export const paises: Pais[] = [
  { slug: "argentina", nombre: "Argentina", bandera: "🇦🇷", color: "#74b9ff" },
  { slug: "bolivia", nombre: "Bolivia", bandera: "🇧🇴", color: "#fdcb6e" },
  { slug: "brasil", nombre: "Brasil", bandera: "🇧🇷", color: "#00b894" },
  { slug: "chile", nombre: "Chile", bandera: "🇨🇱", color: "#d63031" },
  { slug: "china", nombre: "China", bandera: "🇨🇳", color: "#d63031" },
  { slug: "colombia", nombre: "Colombia", bandera: "🇨🇴", color: "#fdcb6e" },
  { slug: "costarica", nombre: "Costa Rica", bandera: "🇨🇷", color: "#0984e3" },
  { slug: "cuba", nombre: "Cuba", bandera: "🇨🇺", color: "#0984e3" },
  { slug: "ecuador", nombre: "Ecuador", bandera: "🇪🇨", color: "#fdcb6e" },
  { slug: "elsalvador", nombre: "El Salvador", bandera: "🇸🇻", color: "#0984e3" },
  { slug: "guatemala", nombre: "Guatemala", bandera: "🇬🇹", color: "#00cec9" },
  { slug: "honduras", nombre: "Honduras", bandera: "🇭🇳", color: "#0984e3" },
  { slug: "mexico", nombre: "México", bandera: "🇲🇽", color: "#00b894" },
  { slug: "nicaragua", nombre: "Nicaragua", bandera: "🇳🇮", color: "#0984e3" },
  { slug: "panama", nombre: "Panamá", bandera: "🇵🇦", color: "#e17055" },
  { slug: "paraguay", nombre: "Paraguay", bandera: "🇵🇾", color: "#d63031" },
  { slug: "peru", nombre: "Perú", bandera: "🇵🇪", color: "#d63031" },
  { slug: "puertorico", nombre: "Puerto Rico", bandera: "🇵🇷", color: "#e17055" },
  { slug: "repdom", nombre: "Rep. Dom.", bandera: "🇩🇴", color: "#0984e3" },
  { slug: "uruguay", nombre: "Uruguay", bandera: "🇺🇾", color: "#74b9ff" },
  { slug: "venezuela", nombre: "Venezuela", bandera: "🇻🇪", color: "#d63031" },
];

export const categorias: Categoria[] = [
  { slug: "mayorista", nombre: "Mayorista", emoji: "🏭", color: "#636e72", badge: 0 },
  { slug: "minorista", nombre: "Minorista", emoji: "🛍️", color: "#00b894", badge: 5 },
  { slug: "distribuidor", nombre: "Distribuidor", emoji: "🚚", color: "#d63031", badge: 0 },
  { slug: "importador", nombre: "Importador", emoji: "🌐", color: "#e17055", badge: 3 },
  { slug: "comics", nombre: "Cómics", emoji: "💬", color: "#a29bfe", badge: 12 },
  { slug: "electronica", nombre: "Electrónica", emoji: "📱", color: "#00cec9", badge: 0 },
  { slug: "accesorios", nombre: "Accesorios", emoji: "🎧", color: "#e17055", badge: 7 },
  { slug: "gaming", nombre: "Gaming", emoji: "🎮", color: "#2d3436", badge: 0 },
  { slug: "tablets", nombre: "Tablets", emoji: "💻", color: "#00b894", badge: 2 },
  { slug: "audio", nombre: "Audio", emoji: "🔊", color: "#00b894", badge: 0 },
  { slug: "cables", nombre: "Cables", emoji: "🔌", color: "#795548", badge: 0 },
  { slug: "ofertas", nombre: "Ofertas", emoji: "🏷️", color: "#e91e8c", badge: 18 },
  { slug: "redes", nombre: "Redes", emoji: "📡", color: "#0984e3", badge: 0 },
  { slug: "seguridad", nombre: "Seguridad", emoji: "🔒", color: "#636e72", badge: 0 },
  { slug: "smartwatch", nombre: "Smartwatch", emoji: "⌚", color: "#795548", badge: 4 },
  { slug: "novedades", nombre: "Novedades", emoji: "✨", color: "#e17055", badge: 9 },
  { slug: "archivos", nombre: "Archivos", emoji: "📁", color: "#0984e3", badge: 0 },
  { slug: "mensajes", nombre: "Mensajes", emoji: "✉️", color: "#00b894", badge: 31 },
  { slug: "soporte", nombre: "Soporte", emoji: "🔧", color: "#e17055", badge: 0 },
  { slug: "config", nombre: "Config", emoji: "⚙️", color: "#636e72", badge: 3 },
];

export const empresas: Empresa[] = [
  // Argentina - Minorista
  {
    slug: "tecnosel",
    nombre: "Tecnosel",
    categoria: "minorista",
    pais: "argentina",
    descripcion: "Venta de celulares y accesorios al por menor. Más de 10 años en el mercado tecnológico de Buenos Aires.",
    telefono: "+54 11 4321-0000",
    whatsapp: "5491143210000",
    email: "ventas@tecnosel.com.ar",
    website: "https://tecnosel.com.ar",
    instagram: "tecnosel",
    facebook: "tecnosel",
    direccion: "Av. Santa Fe 1234, CABA, Argentina",
    logoColor: "#0984e3",
    logoText: "TCNO\nSEL",
    badge: 3,
    destacado: false,
    tags: ["Celulares", "Accesorios", "Garantía oficial"],
    catalogos: [
      { nombre: "Catálogo Smartphones 2024", url: "#" },
      { nombre: "Accesorios y fundas", url: "#" },
    ],
  },
  {
    slug: "celuventas",
    nombre: "Celuventas",
    categoria: "minorista",
    pais: "argentina",
    descripcion: "Especialistas en venta de smartphones nuevos y usados. Financiación en cuotas sin interés.",
    telefono: "+54 11 5555-1234",
    whatsapp: "5491155551234",
    email: "info@celuventas.com.ar",
    instagram: "celuventas",
    direccion: "Av. Corrientes 2000, CABA",
    logoColor: "#00b894",
    logoText: "VENTAS",
    badge: 0,
    tags: ["Nuevos", "Usados", "Financiación"],
    catalogos: [{ nombre: "Stock disponible", url: "#" }],
  },
  {
    slug: "tecnolaser",
    nombre: "Tecnolaser",
    categoria: "minorista",
    pais: "argentina",
    descripcion: "Tecnología de punta con el mejor servicio postventa de la zona norte.",
    telefono: "+54 11 4789-5600",
    whatsapp: "5491147895600",
    email: "ventas@tecnolaser.com.ar",
    instagram: "tecnolaser",
    direccion: "Shopping Nordelta, Tigre, Bs As",
    logoColor: "#d63031",
    logoText: "LASER",
    badge: 7,
    premium: true,
    tags: ["Premium", "Zona Norte", "Postventa"],
    catalogos: [
      { nombre: "Catálogo iPhone", url: "#" },
      { nombre: "Catálogo Samsung", url: "#" },
      { nombre: "Wearables 2024", url: "#" },
    ],
  },
  {
    slug: "compuventas",
    nombre: "Compuventas",
    categoria: "minorista",
    pais: "argentina",
    descripcion: "Computadoras, tablets y celulares al mejor precio.",
    telefono: "+54 11 3344-5566",
    whatsapp: "5491133445566",
    email: "ventas@compuventas.ar",
    instagram: "compuventas",
    logoColor: "#a29bfe",
    logoText: "COMPU",
    badge: 0,
    tags: ["PC", "Tablets", "Celulares"],
    catalogos: [],
  },
  {
    slug: "merlocom",
    nombre: "Merlo Com.",
    categoria: "minorista",
    pais: "argentina",
    descripcion: "Tu tienda de tecnología en Merlo. Celulares, accesorios y reparaciones.",
    telefono: "+54 220 400-1234",
    whatsapp: "5492204001234",
    email: "merlocom@gmail.com",
    instagram: "merlocom",
    direccion: "Av. San Martín 567, Merlo, Bs As",
    logoColor: "#00cec9",
    logoText: "MERLO\nCOM",
    badge: 2,
    tags: ["Merlo", "Reparaciones", "Accesorios"],
    catalogos: [],
  },
  {
    slug: "telgaston",
    nombre: "Tel. Gastón",
    categoria: "minorista",
    pais: "argentina",
    descripcion: "Gastón, tu especialista de confianza en telefonía celular desde 2010.",
    telefono: "+54 11 2233-4455",
    whatsapp: "5491122334455",
    email: "gaston@telgaston.com",
    instagram: "telgaston",
    logoColor: "#e17055",
    logoText: "GASTÓN",
    badge: 0,
    tags: ["Confianza", "Personal", "Celulares"],
    catalogos: [],
  },
  {
    slug: "megacell",
    nombre: "MegaCell",
    categoria: "minorista",
    pais: "argentina",
    descripcion: "Stock mayorista disponible para minoristas. Envíos a todo el país. Precios imbatibles en celulares y accesorios.",
    telefono: "+54 11 6677-8899",
    whatsapp: "5491166778899",
    email: "ventas@megacell.com.ar",
    website: "https://megacell.com.ar",
    instagram: "megacell",
    facebook: "megacellarg",
    direccion: "Once, CABA, Argentina",
    logoColor: "#00b894",
    logoText: "M≡",
    badge: 5,
    patrocinado: true,
    tags: ["Stock mayorista", "Envíos", "Todo el país"],
    catalogos: [
      { nombre: "Lista de precios Julio 2024", url: "#" },
      { nombre: "Catálogo accesorios", url: "#" },
    ],
  },
  {
    slug: "techzone",
    nombre: "TechZone",
    categoria: "minorista",
    pais: "argentina",
    descripcion: "La zona tech más grande de Córdoba. Celulares, gaming y más.",
    telefono: "+54 351 555-7777",
    whatsapp: "5493515557777",
    email: "info@techzone.com.ar",
    instagram: "techzone_cor",
    direccion: "Patio Olmos, Córdoba Capital",
    logoColor: "#fdcb6e",
    logoText: "TZ",
    badge: 0,
    tags: ["Córdoba", "Gaming", "Celulares"],
    catalogos: [],
  },
  {
    slug: "celularesya",
    nombre: "Celulares Ya",
    categoria: "minorista",
    pais: "argentina",
    descripcion: "Celulares ya mismo, al mejor precio. Retiro en el día o envío express.",
    telefono: "+54 11 9988-7766",
    whatsapp: "5491199887766",
    email: "hola@celularesya.com",
    instagram: "celularesya",
    logoColor: "#d63031",
    logoText: "CY\nCELULARES YA",
    badge: 0,
    tags: ["Express", "Retiro en el día", "Precios"],
    catalogos: [],
  },
  {
    slug: "smartshop",
    nombre: "SmartShop",
    categoria: "minorista",
    pais: "argentina",
    descripcion: "Smart shopping para gente inteligente. Los mejores gadgets y celulares.",
    telefono: "+54 11 1122-3344",
    whatsapp: "5491111223344",
    email: "info@smartshop.com.ar",
    instagram: "smartshop_ar",
    logoColor: "#0984e3",
    logoText: "SMART\nSHOP",
    badge: 0,
    tags: ["Gadgets", "Smartwatch", "Celulares"],
    catalogos: [],
  },
  {
    slug: "digimundo",
    nombre: "DigiMundo",
    categoria: "minorista",
    pais: "argentina",
    descripcion: "Tecnología y conectividad para toda la región. Soluciones integrales para empresas y particulares.",
    telefono: "+54 11 4000-9999",
    whatsapp: "5491140009999",
    email: "ventas@digimundo.com.ar",
    website: "https://digimundo.com.ar",
    instagram: "digimundo",
    facebook: "digimundo",
    direccion: "Microcentro, CABA",
    logoColor: "#00b894",
    logoText: "DIGI\nMUNDO",
    badge: 0,
    premium: true,
    tags: ["Empresas", "Conectividad", "Integral"],
    catalogos: [
      { nombre: "Soluciones empresariales", url: "#" },
      { nombre: "Catálogo B2B 2024", url: "#" },
    ],
  },
  {
    slug: "movilcenter",
    nombre: "MovilCenter",
    categoria: "minorista",
    pais: "argentina",
    descripcion: "Centro de soluciones móviles. Reparación, venta y accesorios.",
    telefono: "+54 11 5544-3322",
    whatsapp: "5491155443322",
    email: "movilcenter@outlook.com",
    instagram: "movilcenter_ar",
    logoColor: "#636e72",
    logoText: "MOVIL\nCENTER",
    badge: 0,
    tags: ["Reparación", "Venta", "Service"],
    catalogos: [],
  },
  {
    slug: "turboPhone",
    nombre: "TurboPhone",
    categoria: "minorista",
    pais: "argentina",
    descripcion: "Velocidad en ventas y atención. El mejor precio garantizado.",
    telefono: "+54 11 7788-9900",
    whatsapp: "5491177889900",
    email: "turbo@turbophone.com.ar",
    instagram: "turbophone",
    logoColor: "#a29bfe",
    logoText: "TURBO",
    badge: 0,
    tags: ["Precio garantizado", "Atención rápida"],
    catalogos: [],
  },
  {
    slug: "nextech",
    nombre: "NexTech",
    categoria: "minorista",
    pais: "argentina",
    descripcion: "Next level technology. Lo último en smartphones y wearables.",
    telefono: "+54 11 2468-1357",
    whatsapp: "5491124681357",
    email: "hola@nextech.com.ar",
    instagram: "nextech_ar",
    facebook: "nextech.argentina",
    logoColor: "#0984e3",
    logoText: "NX\nNEXTECH",
    badge: 4,
    destacado: true,
    tags: ["Wearables", "Smartphones", "Premium"],
    catalogos: [
      { nombre: "Colección Premium 2024", url: "#" },
    ],
  },
  {
    slug: "celplus",
    nombre: "CelPlus",
    categoria: "minorista",
    pais: "argentina",
    descripcion: "Más celulares, más opciones, más precio. Tu tienda plus de tecnología.",
    telefono: "+54 11 3131-4141",
    whatsapp: "5491131314141",
    email: "info@celplus.com.ar",
    logoColor: "#d63031",
    logoText: "+\nCEL+",
    badge: 0,
    tags: ["Variedad", "Precios", "Opciones"],
    catalogos: [],
  },
  {
    slug: "phoneria",
    nombre: "Phoneria",
    categoria: "minorista",
    pais: "argentina",
    descripcion: "Especialistas en telefonía. Asesoramiento personalizado y garantía.",
    telefono: "+54 11 6969-4242",
    whatsapp: "5491169694242",
    email: "phoneria@gmail.com",
    instagram: "phoneria_ar",
    logoColor: "#00b894",
    logoText: "PH\nPHONERIA",
    badge: 0,
    tags: ["Asesoramiento", "Garantía", "Telefonía"],
    catalogos: [],
  },
  {
    slug: "gigastore",
    nombre: "GigaStore",
    categoria: "minorista",
    pais: "argentina",
    descripcion: "Una gigastore de tecnología. Todo en un solo lugar.",
    telefono: "+54 11 5050-7070",
    whatsapp: "5491150507070",
    email: "ventas@gigastore.com.ar",
    instagram: "gigastore_ar",
    logoColor: "#a29bfe",
    logoText: "G\nGIGASTORE",
    badge: 0,
    tags: ["Todo en uno", "Gran variedad"],
    catalogos: [],
  },
  {
    slug: "alphacell",
    nombre: "AlphaCell",
    categoria: "minorista",
    pais: "argentina",
    descripcion: "Liderando el mercado tech desde 2015. Calidad alpha en cada venta.",
    telefono: "+54 11 1414-2525",
    whatsapp: "5491114142525",
    email: "alpha@alphacell.com.ar",
    instagram: "alphacell",
    logoColor: "#d63031",
    logoText: "ALPHA\nCELL",
    badge: 0,
    tags: ["Líder", "Calidad", "2015"],
    catalogos: [],
  },
  {
    slug: "techpro",
    nombre: "TechPro",
    categoria: "minorista",
    pais: "argentina",
    descripcion: "Profesionales en tecnología. Para clientes que buscan lo mejor.",
    telefono: "+54 11 8080-3030",
    whatsapp: "5491180803030",
    email: "pro@techpro.com.ar",
    instagram: "techpro_ar",
    logoColor: "#0984e3",
    logoText: "T|P",
    badge: 0,
    destacado: true,
    tags: ["Profesional", "Distribuidor oficial", "Buenos Aires"],
    catalogos: [
      { nombre: "Catálogo Pro 2024", url: "#" },
    ],
  },
  {
    slug: "celfacil",
    nombre: "CelFácil",
    categoria: "minorista",
    pais: "argentina",
    descripcion: "Comprar tecnología nunca fue tan fácil. Simple, rápido y seguro.",
    telefono: "+54 11 7777-1111",
    whatsapp: "5491177771111",
    email: "facil@celfacil.com.ar",
    instagram: "celfacil",
    logoColor: "#00b894",
    logoText: "CEL\nFÁCIL",
    badge: 0,
    tags: ["Simple", "Rápido", "Seguro"],
    catalogos: [],
  },

  // Argentina - Mayorista
  {
    slug: "distribuidora-norte",
    nombre: "Distribuidora Norte",
    categoria: "mayorista",
    pais: "argentina",
    descripcion: "Distribución mayorista de celulares y accesorios para toda la región norte.",
    telefono: "+54 381 400-5000",
    whatsapp: "5493814005000",
    email: "mayorista@disnorte.com.ar",
    logoColor: "#636e72",
    logoText: "DN",
    badge: 0,
    tags: ["Norte", "Mayorista", "Distribución"],
    catalogos: [{ nombre: "Lista mayorista", url: "#" }],
  },
  {
    slug: "wholesale-tech",
    nombre: "Wholesale Tech",
    categoria: "mayorista",
    pais: "argentina",
    descripcion: "El mayorista más grande de tecnología en Argentina.",
    telefono: "+54 11 4000-8000",
    whatsapp: "5491140008000",
    email: "ventas@wholesaletech.com.ar",
    logoColor: "#2d3436",
    logoText: "WT",
    badge: 2,
    patrocinado: true,
    tags: ["Mayorista", "Gran volumen", "Nacional"],
    catalogos: [],
  },

  // Argentina - Distribuidor
  {
    slug: "techdist-ar",
    nombre: "TechDist AR",
    categoria: "distribuidor",
    pais: "argentina",
    descripcion: "Distribuidor oficial de las principales marcas de tecnología.",
    telefono: "+54 11 5000-3000",
    whatsapp: "5491150003000",
    email: "dist@techdist.com.ar",
    logoColor: "#d63031",
    logoText: "TD",
    badge: 0,
    tags: ["Oficial", "Marcas", "Distribuidor"],
    catalogos: [],
  },

  // Argentina - Accesorios
  {
    slug: "accesorios-max",
    nombre: "Accesorios Max",
    categoria: "accesorios",
    pais: "argentina",
    descripcion: "El mayor catálogo de accesorios para celulares de Argentina.",
    telefono: "+54 11 3000-7000",
    whatsapp: "5491130007000",
    email: "info@accesoriosmax.com.ar",
    logoColor: "#e17055",
    logoText: "MAX",
    badge: 7,
    tags: ["Fundas", "Cables", "Cargadores"],
    catalogos: [{ nombre: "Catálogo accesorios", url: "#" }],
  },

  // México - Minorista
  {
    slug: "celmax-mx",
    nombre: "CelMax México",
    categoria: "minorista",
    pais: "mexico",
    descripcion: "Los mejores precios en celulares en toda la República Mexicana.",
    telefono: "+52 55 1234-5678",
    whatsapp: "525512345678",
    email: "ventas@celmax.com.mx",
    instagram: "celmax_mx",
    logoColor: "#00b894",
    logoText: "CM",
    badge: 3,
    tags: ["México", "Celulares", "Precios"],
    catalogos: [],
  },
  {
    slug: "techmexico",
    nombre: "TechMéxico",
    categoria: "minorista",
    pais: "mexico",
    descripcion: "Tecnología de vanguardia para el mercado mexicano.",
    telefono: "+52 33 9876-5432",
    whatsapp: "523398765432",
    email: "hola@techmexico.com.mx",
    instagram: "techmexico",
    logoColor: "#d63031",
    logoText: "TM",
    badge: 0,
    tags: ["Guadalajara", "Vanguardia", "Tech"],
    catalogos: [],
  },
  {
    slug: "movil-store-mx",
    nombre: "MovilStore MX",
    categoria: "mayorista",
    pais: "mexico",
    descripcion: "Distribución mayorista al por mayor en toda México.",
    telefono: "+52 55 8888-9999",
    whatsapp: "525588889999",
    email: "mayoreo@movilstore.com.mx",
    logoColor: "#a29bfe",
    logoText: "MS",
    badge: 1,
    tags: ["Mayoreo", "Nacional", "México"],
    catalogos: [],
  },

  // Colombia - Minorista
  {
    slug: "celcol",
    nombre: "CelCol",
    categoria: "minorista",
    pais: "colombia",
    descripcion: "Tu tienda de celulares en Colombia. Bogotá y toda la región.",
    telefono: "+57 601 234-5678",
    whatsapp: "576012345678",
    email: "ventas@celcol.com.co",
    instagram: "celcol_co",
    logoColor: "#fdcb6e",
    logoText: "CC",
    badge: 2,
    tags: ["Bogotá", "Colombia", "Celulares"],
    catalogos: [],
  },
  {
    slug: "tecno-colombia",
    nombre: "TecnoColombia",
    categoria: "distribuidor",
    pais: "colombia",
    descripcion: "Distribución de tecnología en todo el territorio colombiano.",
    telefono: "+57 604 555-6666",
    whatsapp: "576045556666",
    email: "dist@tecnocolombia.com.co",
    logoColor: "#00b894",
    logoText: "TC",
    badge: 0,
    tags: ["Distribución", "Nacional", "Colombia"],
    catalogos: [],
  },

  // Chile - Minorista
  {
    slug: "celchile",
    nombre: "CelChile",
    categoria: "minorista",
    pais: "chile",
    descripcion: "Los mejores celulares de Chile al mejor precio.",
    telefono: "+56 2 2345-6789",
    whatsapp: "56222345678",
    email: "ventas@celchile.cl",
    instagram: "celchile",
    logoColor: "#d63031",
    logoText: "CH",
    badge: 1,
    tags: ["Santiago", "Chile", "Celulares"],
    catalogos: [],
  },
  {
    slug: "techsur",
    nombre: "TechSur",
    categoria: "mayorista",
    pais: "chile",
    descripcion: "Mayorista de tecnología para el cono sur.",
    telefono: "+56 2 9999-8888",
    whatsapp: "56229999888",
    email: "mayorista@techsur.cl",
    logoColor: "#0984e3",
    logoText: "TS",
    badge: 0,
    tags: ["Cono Sur", "Mayorista", "Chile"],
    catalogos: [],
  },

  // Brasil - Minorista
  {
    slug: "celubrasil",
    nombre: "CeluBrasil",
    categoria: "minorista",
    pais: "brasil",
    descripcion: "Tecnologia e celulares para todo o Brasil.",
    telefono: "+55 11 9123-4567",
    whatsapp: "5511912345678",
    email: "vendas@celubrasil.com.br",
    instagram: "celubrasil",
    logoColor: "#00b894",
    logoText: "CB",
    badge: 4,
    tags: ["São Paulo", "Brasil", "Celulares"],
    catalogos: [],
  },

  // Perú - Minorista
  {
    slug: "techperu",
    nombre: "TechPerú",
    categoria: "minorista",
    pais: "peru",
    descripcion: "La mejor tecnología para el mercado peruano. Lima y provincias.",
    telefono: "+51 1 234-5678",
    whatsapp: "51112345678",
    email: "ventas@techperu.com.pe",
    instagram: "techperu",
    logoColor: "#d63031",
    logoText: "TP",
    badge: 0,
    tags: ["Lima", "Perú", "Nacional"],
    catalogos: [],
  },

  // Venezuela - Minorista
  {
    slug: "tecnovenezuela",
    nombre: "TecnoVenezuela",
    categoria: "minorista",
    pais: "venezuela",
    descripcion: "Tecnología accesible para Venezuela.",
    telefono: "+58 212 555-1234",
    whatsapp: "582125551234",
    email: "info@tecnovenezuela.com",
    instagram: "tecnovenezuela",
    logoColor: "#d63031",
    logoText: "TV",
    badge: 0,
    tags: ["Caracas", "Venezuela", "Tech"],
    catalogos: [],
  },
];

export function getPais(slug: string): Pais | undefined {
  return paises.find((p) => p.slug === slug);
}

export function getCategoria(slug: string): Categoria | undefined {
  return categorias.find((c) => c.slug === slug);
}

export function getEmpresasByPaisAndCategoria(pais: string, categoria: string): Empresa[] {
  return empresas.filter((e) => e.pais === pais && e.categoria === categoria);
}

export function getEmpresa(pais: string, categoria: string, slug: string): Empresa | undefined {
  return empresas.find((e) => e.pais === pais && e.categoria === categoria && e.slug === slug);
}

export function getCategoriasConEmpresas(pais: string): Categoria[] {
  const cats = new Set(empresas.filter((e) => e.pais === pais).map((e) => e.categoria));
  return categorias.filter((c) => cats.has(c.slug));
}
